version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - moa_postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    command: >
      bash -c "
        docker-entrypoint.sh postgres &
        until pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} > /dev/null 2>&1; do
          sleep 2;
        done;
        psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /docker-entrypoint-initdb.d/02_data_import.sql;
        wait
      "
    networks:
      - app-network

  # Redis Cache
  redis:
    image: redis:8.0.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - moa_redis_data:/data
    networks:
      - app-network

# Volume & Network 설정
volumes:
  moa_postgres_data:
  moa_redis_data:

networks:
  app-network:
    driver: bridge